### ISSUE TITLE
downgrade

### ISSUE THREAD

**Issue by bngthub** [rocky-linux/wiki.rockylinux.org#115]
I want to downgrade the rocky 9.4 to 9.2 can it be possible to do that if possible, please help me to do that
![Capture1](https://github.com/user-attachments/assets/809cb79a-dfc4-46b0-bdca-46fbdb165f3b)

**Comment by nazunalika** [comment]
Hello.

This is for issues with our wiki, and not the distribution. Community support can be obtained at our [forums](https://forums.rockylinux.org) or [mattermost](https://chat.rockylinux.org). 

As for your question, no, it is not possible to downgrade to 9.2 cleanly. Rocky Linux 9.2 is also not supported. Please see [the version guide](https://wiki.rockylinux.org/rocky/version/#__tabbed_1_2) for more information.

If you must use an older release, you can go to [the vault](https://dl.rockylinux.org/vault/rocky/), obtain a Rocky Linux 9.2 DVD or minimal ISO and install that way. You will then need to configure your repositories to point to the vault repositories. Note that the project nor the community can support you if you are using an older release. See the [repositories](https://wiki.rockylinux.org/rocky/repo/#vault) wiki for more information.
